# Introduction

Throughout this notebook I will be utilizing macroeconomic data to analyse the short term outlook of the US economy and whether one should be optimistic or pessemistic considering the existing data. However, it is important to note that there is an abundance of macroeconomic data available and by looking at only a few statistics, indicators, and visualizations it is impossible to portray a truly realistic image. In hopes of working against this, I will be looking at indicators that are considering highly significant and useful by economists & academics. These indicators include, GDP, Trade, Unemployment, the yield curve, and Debt.

**Section 1**

We will start with a more wholistic outlook, looking at the global framework and its current economic status. This will give us an important understanding of how things have progressed over the past centuries and the impact of globalization, but also portraying the significance of the United States economy in the world, especially in the past century. We will then look at where we are in the economic business cycle, meaning are we currently in an expansion or a contraction, and how long these periods tend to last. 

**Section 2**

We will then dive into the influential US economic indicators and the difference between leading and lagging indicators (We will get into the definition of each later on). However, for the sake of this project, we will only be looking at one leading and lagging indicators, as there are over 16 major indicators. 

For the lagging indicator we will be focusing on the unemployment rate, while also explaining the significance of structural unemployment in an economy. 

**Section 3**

After looking at the unemployment rate we will then look at a leading indicator: the yield curve. Finally, I will look at the extremely rapid expansion of US Debt, the achilles heel of the US economy, concluding with it's significance in the global framework and the future and whether or not we are optimistic about it.

# Data Sources
 There is a broad array of macroeconomic data available, both easily accesible and prepared for economic analysts to analyse. For this project my sources included: 
 
 - My World in Data
 - World Trade Organization
 - The Beureu of Labor Statistics 
 - International Labbor Organization
 - Federal Reserve Economic Data
 - The National Bureau of Economic Research

Most of the datasets were accessible as csv and excel files however for the purposes of this project I scraped a web page from the National Bureau of Economic Research.

In [470]:
#make sure all requirements for visualization are installed
!pip install wordcloud
!pip install msgpack
!pip install wordcloud
!pip install folium
!pip install plotly

Requirement already satisfied: wordcloud in /anaconda3/lib/python3.6/site-packages (1.4.1)
Requirement already satisfied: pillow in /anaconda3/lib/python3.6/site-packages (from wordcloud) (5.1.0)
Requirement already satisfied: numpy>=1.6.1 in /anaconda3/lib/python3.6/site-packages (from wordcloud) (1.14.3)
Requirement already satisfied: matplotlib in /anaconda3/lib/python3.6/site-packages (from wordcloud) (2.2.2)
Requirement already satisfied: cycler>=0.10 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (2.7.3)
Requirement already satisfied: pytz in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (2018.4)
Requirement already satisfied: six>=1.10 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (1.0.1)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->wordcloud) (39.1.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: msgpack in /anaconda3/lib/python3.6/site-packages (0.5.6)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: wordcloud in /anaconda3/lib/python3.6/site-packages (1.4.1)
Requirement already satisfied: matplotlib in /anaconda3/lib/python3.6/site-packages (from wordcloud) (2.2.2)
Requirement already satisfied: pillow in /anaconda3/lib/python3.6/site-packages (from wordcloud) (5.1.0)
Requirement already satisfied: numpy>=1.6.1 in /anaconda3/lib/python3.6/site-packages (from wordcloud) (1.14.3)
Requirement already satisfied: cycler>=0.10 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (2.7.3)
Requirement already satisfied: pytz in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (2018.4)
Requirement already satisfied: six>=1.10 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud) (1.0.1)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->wordcloud) (39.1.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: folium in /anaconda3/lib/python3.6/site-packages (0.5.0)
Requirement already satisfied: requests in /anaconda3/lib/python3.6/site-packages (from folium) (2.18.4)
Requirement already satisfied: jinja2 in /anaconda3/lib/python3.6/site-packages (from folium) (2.10)
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from folium) (1.11.0)
Requirement already satisfied: branca in /anaconda3/lib/python3.6/site-packages (from folium) (0.3.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.6/site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.6/site-packages (from requests->folium) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.6/site-packages (from requests->folium) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.6/site-packages (from requests->folium) (2018.4.16)
Requirement already satisfied: MarkupSafe>=0.23 in /anaconda3/lib/python3.6/site-packages (from jinja2->folium) (1.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: plotly in /anaconda3/lib/python3.6/site-packages (3.0.0)
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from plotly) (1.11.0)
Requirement already satisfied: decorator>=4.0.6 in /anaconda3/lib/python3.6/site-packages (from plotly) (4.3.0)
Requirement already satisfied: pytz in /anaconda3/lib/python3.6/site-packages (from plotly) (2018.4)
Requirement already satisfied: requests in /anaconda3/lib/python3.6/site-packages (from plotly) (2.18.4)
Requirement already satisfied: nbformat>=4.2 in /anaconda3/lib/python3.6/site-packages (from plotly) (4.4.0)
Requirement already satisfied: retrying>=1.3.3 in /anaconda3/lib/python3.6/site-packages (from plotly) (1.3.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.6/site-packages (from requests->plotly) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.6/site-packages (from requests->plotly) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.6/site-packages (from requests->plotly) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.6/site-packages (from requests->plotly) (2018.4.16)
Requirement already satisfied: ipython_genutils in /anaconda3/lib/python3.6/site-packages (from nbformat>=4.2->plotly) (0.2.0)
Requirement already satisfied: traitlets>=4.1 in /anaconda3/lib/python3.6/site-packages (from nbformat>=4.2->plotly) (4.3.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /anaconda3/lib/python3.6/site-packages (from nbformat>=4.2->plotly) (2.6.0)
Requirement already satisfied: jupyter_core in /anaconda3/lib/python3.6/site-packages (from nbformat>=4.2->plotly) (4.4.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [256]:
#importing plotly, matplotlib, plotly, seaborn etc. 

import matplotlib.pyplot as plt
import matplotlib
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)
import seaborn as sns 
import numpy as np
import pandas as pd
import numpy as np
import random as rnd
import re
import io
from sklearn.metrics import confusion_matrix
import seaborn as sns
from IPython.display import HTML

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

!pip install -U scikit-learn
from sklearn.preprocessing import MinMaxScaler
import numpy
import plotly
plotly.offline.init_notebook_mode(connected=True)
import plotly
import plotly.offline as py
import plotly.graph_objs as go

py.init_notebook_mode()

# Section 1

To start, we will look at a few visualizations regarding global trade and GDP. We will then look at the significance of the US economy and where it stands in the business cycle.

In [482]:
#assign variable for world trade csv file of world trade exports growth create pandas dataframe
World_Trade_data = 'world-trade-exports-constant-prices.csv'
world_trade = pd.read_csv(World_Trade_data)

#columns name
#change column name from 'World Trade (relative to 1913) ( )' to 'World Trade'
world_trade.columns = ['Index','Unnamed:','Entity','Code','Year','World Trade']
print(world_trade.keys())

# assign variable for world GDP csv file, create pd df
world_GDP_data = 'World GDP 1980.xlsx'
world_GDP = pd.read_excel(world_GDP_data)
print(world_GDP.keys())

#assign variable for US GDP xls file and create pd df
US_GDP_data = 'US GDP.xls'
US_GDP  = pd.read_excel(US_GDP_data)
print(US_GDP.keys())

Index(['Index', 'Unnamed:', 'Entity', 'Code', 'Year', 'World Trade'], dtype='object')
Index(['World GDP', 'Year'], dtype='object')
Index(['Year', 'GDP'], dtype='object')

In [483]:
#see data in table setting
print(world_trade)
print(world_GDP)
print(US_GDP)

     Index  Unnamed: Entity      Code  Year  World Trade
0        0         0  World  OWID_WRL  1800     2.140985
1        1         1  World  OWID_WRL  1801     2.404047
2        2         2  World  OWID_WRL  1802     3.023091
3        3         3  World  OWID_WRL  1803     2.625805
4        4         4  World  OWID_WRL  1804     2.739896
5        5         5  World  OWID_WRL  1805     2.452424
6        6         6  World  OWID_WRL  1806     2.602441
7        7         7  World  OWID_WRL  1807     2.613828
8        8         8  World  OWID_WRL  1808     1.775507
9        9         9  World  OWID_WRL  1809     2.600543
10      10        10  World  OWID_WRL  1810     2.522553
11      11        11  World  OWID_WRL  1811     2.159217
12      12        12  World  OWID_WRL  1812     2.115038
13      13        13  World  OWID_WRL  1813     2.174441
14      14        14  World  OWID_WRL  1814     2.267282
15      15        15  World  OWID_WRL  1815     2.930514
16      16        16  World  OWID_WRL  1816     3.017644
17      17        17  World  OWID_WRL  1817     3.263396
18      18        18  World  OWID_WRL  1818     3.065482
19      19        19  World  OWID_WRL  1819     2.825090
20      20        20  World  OWID_WRL  1820     3.357308
21      21        21  World  OWID_WRL  1821     3.381799
22      22        22  World  OWID_WRL  1822     3.547340
23      23        23  World  OWID_WRL  1823     3.703233
24      24        24  World  OWID_WRL  1824     4.131801
25      25        25  World  OWID_WRL  1825     3.967435
26      26        26  World  OWID_WRL  1826     4.430824
27      27        27  World  OWID_WRL  1827     4.586846
28      28        28  World  OWID_WRL  1828     4.827780
29      29        29  World  OWID_WRL  1829     4.966623
..     ...       ...    ...       ...   ...          ...
174    174       174  World  OWID_WRL  1985  1325.380000
175    175       175  World  OWID_WRL  1986  1378.396000
176    176       176  World  OWID_WRL  1987  1454.207000
177    177       177  World  OWID_WRL  1988  1577.815000
178    178       178  World  OWID_WRL  1989  1678.795000
179    179       179  World  OWID_WRL  1990  1744.268000
180    180       180  World  OWID_WRL  1991  1808.806000
181    181       181  World  OWID_WRL  1992  1895.629000
182    182       182  World  OWID_WRL  1993  1979.036000
183    183       183  World  OWID_WRL  1994  2163.087000
184    184       184  World  OWID_WRL  1995  2323.155000
185    185       185  World  OWID_WRL  1996  2441.636000
186    186       186  World  OWID_WRL  1997  2688.241000
187    187       187  World  OWID_WRL  1998  2811.900000
188    188       188  World  OWID_WRL  1999  2941.248000
189    189       189  World  OWID_WRL  2000  3258.903000
190    190       190  World  OWID_WRL  2001  3252.120000
191    191       191  World  OWID_WRL  2002  3364.484000
192    192       192  World  OWID_WRL  2003  3552.919000
193    193       193  World  OWID_WRL  2004  3898.920000
194    194       194  World  OWID_WRL  2005  4154.229000
195    195       195  World  OWID_WRL  2006  4511.168000
196    196       196  World  OWID_WRL  2007  4803.425000
197    197       197  World  OWID_WRL  2008  4914.792000
198    198       198  World  OWID_WRL  2009  4320.877000
199    199       199  World  OWID_WRL  2010  4928.651000
200    200       200  World  OWID_WRL  2011  4557.166350
201    201       201  World  OWID_WRL  2012  4418.939503
202    202       202  World  OWID_WRL  2013  4444.857037
203    203       203  World  OWID_WRL  2014  4427.578681

[204 rows x 6 columns]
    World GDP  Year
0   11136.332  1980
1   11389.413  1981
2   11178.209  1982
3   11482.978  1983
4   11896.782  1984
5   12442.661  1985
6   14664.532  1986
7   16888.238  1987
8   18997.254  1988
9   19989.023  1989
10  23453.702  1990
11  24345.305  1991
12  25180.185  1992
13  25871.347  1993
14  27818.373  1994
15  31022.166  1995
16  31881.594  1996
17  31812.726  1997
18  31663.538  1998
19  32782.879  1999
20  33867.113  2000
21  33619.953  2001
22  34745.092  2002
23  39015.900  2003
24  43919.510  2004
25  47580.891  2005
26  51509.014  2006
27  58115.313  2007
28  63721.645  2008
29  60337.197  2009
30  65960.280  2010
31  73165.347  2011
32  74535.411  2012
33  76596.140  2013
34  78663.165  2014
35  74429.034  2015
36  75485.006  2016
37  79865.481  2017
38  87504.567  2018
39        NaN  2019
40        NaN  2020
41        NaN  2021
42        NaN  2022
43        NaN  2023
    Year        GDP
0   1929    104.560
1   1930     92.167
2   1931     77.406
3   1932     59.532
4   1933     57.165
5   1934     66.812
6   1935     74.259
7   1936     84.854
8   1937     93.029
9   1938     87.387
10  1939     93.473
11  1940    102.946
12  1941    129.356
13  1942    165.997
14  1943    203.122
15  1944    224.550
16  1945    228.173
17  1946    227.812
18  1947    249.945
19  1948    274.807
20  1949    272.827
21  1950    300.198
22  1951    347.294
23  1952    367.728
24  1953    389.739
25  1954    391.146
26  1955    426.175
27  1956    450.130
28  1957    474.851
29  1958    482.045
..   ...        ...
59  1988   5252.629
60  1989   5657.693
61  1990   5979.589
62  1991   6174.043
63  1992   6539.299
64  1993   6878.718
65  1994   7308.755
66  1995   7664.060
67  1996   8100.201
68  1997   8608.515
69  1998   9089.168
70  1999   9660.624
71  2000  10284.779
72  2001  10621.824
73  2002  10977.514
74  2003  11510.670
75  2004  12274.928
76  2005  13093.726
77  2006  13855.888
78  2007  14477.635
79  2008  14718.582
80  2009  14418.739
81  2010  14964.372
82  2011  15517.926
83  2012  16155.255
84  2013  16691.517
85  2014  17427.609
86  2015  18120.714
87  2016  18624.475
88  2017  19390.605

[89 rows x 2 columns]

In [486]:
world_trade.to_csv(World_Trade_data)
world_trade.columns = ['Index','Unnamed:','Entity','Code','Year','World Trade']

#assign x and y
x1 = world_trade['Year']
y1 = world_trade['World Trade']

#create trace
trace = go.Scatter(
    x = x1,
    y = y1
)

data = [trace]

#change layout and add titles
layout = dict(title = 'World Exports Since 1800',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'Global Exports Relative to 1913'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig)

Looking at the graph above, we see that global trade which is measured by world exports is quite constant and does not increase by a significant factor for over a century. In fact, even at the peak of the British Empire, trade and globalization were nowhere near the level they are at today. At the turn of the 20th century, global trade explodes, growing exponentially. In fact, since 1950, world trade grew at a total factor of 43x.

In [487]:
world_GDP_data = 'World GDP 1980.xlsx'
world_GDP = pd.read_excel(world_GDP_data)

x2 = world_GDP['Year']
y2 = world_GDP['World GDP']

trace = go.Scatter(
    x = x2,
    y = y2
)

data = [trace]

layout = dict(title = 'World GDP Since 1980',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'World GDP ($)'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig)

As the world became more integrated through trade, GDP started to rise across nations. Following WWII, the 'Second Wave of Globalization" took place, with nations becoming more open to trade and customs unions/free trade areas, such as NAFTA and the EU began the process of being established. While world trade grew a factor of 43x, World GDP grew a total of 11x since 1950.

In [488]:
US_GDP_data = 'US GDP.xls'
US_GDP = pd.read_excel(US_GDP_data)

x3 = US_GDP['Year']
y3 = US_GDP['GDP']

trace = go.Scatter(
    x = x3,
    y = y3
)

data = [trace]

layout = dict(title = 'US GDP Since 1930',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'US GDP ($)'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig)

Finally, the US started to grow its economy at a very rapid rate after WWII. Having come out of the war victorious and becoming the world's superpower, the US GDP grew at a factor 8x since 1950, only 3x less than the rest of the world combined. Thus, the US took the spotlight to beome one of, if not the most important economy in the world, making up about 23% of World GDP. Now, it is important to understnad where we are in today's economy and we can do so by looking at the business cycle.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Are we in a good or bad time? Are people spending or saving? What time of fiscal and monetary policies are being introduced? Without going to far in depth, it is a good idea to simply look at the business cycle, meaning are we in a recession or an expansion? And how far are we into a contraction/expansion. The following table shows us where we are in the business cycle.

In [489]:
#install beautifulsoup

!pip install beautifulsoup4
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

Requirement already satisfied: beautifulsoup4 in /anaconda3/lib/python3.6/site-packages (4.6.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [319]:
#make a get request to retrieve the US Business Cycle Expansions and Contractions page

US_Business_Cycle = requests.get('http://www.nber.org/cycles.html')
soup = BeautifulSoup(US_Business_Cycle.text, 'html.parser')

#create seperate lists to add data to.

listone=[]
listtwo=[]
listthree=[]
listfour=[]
listfive=[]


#find div that has attributes that are equal to align:center
mainblock = soup.find('div', attrs= {'align':'center'})
tableint = mainblock.find('table')

#this is going to return the row with valign:top
rowint = tableint.findAll('tr', attrs={'valign':'top'})
countt=0
for z in rowint:
#find table that is equal to valign:top that I want since there are three of them    
    if countt <=1:
        countt = countt + 1
    else:
        alldata = z.findAll('td')
        countr = 0
        cf=0
        for x in alldata:
            if cf >= 0:
                celldata = x.get_text()
            
                if countr == 0:
                    print('Column1')
                    print(type(celldata))
                    
                    listone = celldata.split('\n')
                    print(listone)

                elif countr == 1:
                    print('Column2')
                    print(str(celldata) + '\n')
                    
                    listtwo = celldata.split('\n')
                    print(listtwo)

                elif countr ==2:
                    print('Column3')
                    print(str(celldata) + '\n')
                    
                    listthree = celldata.split('\n')
                    print(listthree)

                elif countr == 3:
                    print('Column4')
                    print(str(celldata) + '\n')
                    
                    listfour = celldata.split('\n')
                    print(listfour)
                
                elif countr == 4:
                    print('Column5')
                    print(str(celldata) + '\n')
                    
                    listfive = celldata.split('\n')
                    print(listfive)
                

                countr = countr+ 1
            else:
                cf = cf + 1

Column1
<class 'str'>
['', '', 'June 1857(II)', 'October 1860(III)', 'April 1865(I)', 'June 1869(II)', 'October 1873(III)', '', 'March 1882(I)', 'March 1887(II)', 'July 1890(III)', 'January 1893(I)', 'December 1895(IV)', '', 'June 1899(III)', 'September 1902(IV)', 'May 1907(II)', 'January 1910(I)', 'January 1913(I)', '', 'August 1918(III)', 'January 1920(I)', 'May 1923(II)', 'October 1926(III)', 'August 1929(III)', '', 'May 1937(II)', 'February 1945(I)', 'November 1948(IV)', 'July 1953(II)', 'August 1957(III)', '', 'April 1960(II)', 'December 1969(IV)', 'November 1973(IV)', 'January 1980(I)', 'July 1981(III)', '', 'July 1990(III)', 'March     2001(I)', 'December 2007 (IV)', '']
Column2

December 1854 (IV)
December 1858 (IV)
June 1861 (III)
December 1867 (I)
December 1870 (IV)
March 1879 (I)

May 1885 (II)
April 1888 (I)
May 1891 (II)
June 1894 (II)
June 1897 (II)

December 1900 (IV)
August 1904 (III)
June 1908 (II)
January 1912 (IV)
December 1914 (IV)

March 1919 (I)
July 1921 (III)
July 1924 (III)
November 1927 (IV)
March 1933 (I)

June 1938 (II)
October 1945 (IV)
October 1949 (IV)
May 1954 (II)
April 1958 (II)

February 1961 (I)
November 1970 (IV)
March 1975 (I)
July 1980 (III)
November 1982 (IV)
March     1991(I)

November 2001 (IV)
June 2009 (II)


['', 'December 1854 (IV)', 'December 1858 (IV)', 'June 1861 (III)', 'December 1867 (I)', 'December 1870 (IV)', 'March 1879 (I)', '', 'May 1885 (II)', 'April 1888 (I)', 'May 1891 (II)', 'June 1894 (II)', 'June 1897 (II)', '', 'December 1900 (IV)', 'August 1904 (III)', 'June 1908 (II)', 'January 1912 (IV)', 'December 1914 (IV)', '', 'March 1919 (I)', 'July 1921 (III)', 'July 1924 (III)', 'November 1927 (IV)', 'March 1933 (I)', '', 'June 1938 (II)', 'October 1945 (IV)', 'October 1949 (IV)', 'May 1954 (II)', 'April 1958 (II)', '', 'February 1961 (I)', 'November 1970 (IV)', 'March 1975 (I)', 'July 1980 (III)', 'November 1982 (IV)', 'March     1991(I)', '', 'November 2001 (IV)', 'June 2009 (II)', '']
Column3

--
18
8
32
18
65

38
13
10
17
18

18
23
13
24
23

7
18
14
13
43

13
8
11
10
8

10
11
16
6
16

8
8
18


['', '--', '18', '8', '32', '18', '65', '', '38', '13', '10', '17', '18', '', '18', '23', '13', '24', '23', '', '7', '18', '14', '13', '43', '', '13', '8', '11', '10', '8', '', '10', '11', '16', '6', '16', '', '8', '8', '18', '']
Column4

--
30
22
46
18
34

36
22
27
20
18

24
21
33
19
12

44
10
22
27
21

50
80
37
45
39

24
106
36
58
12

92
120
73


['', '--', '30', '22', '46', '18', '34', '', '36', '22', '27', '20', '18', '', '24', '21', '33', '19', '12', '', '44', '10', '22', '27', '21', '', '50', '80', '37', '45', '39', '', '24', '106', '36', '58', '12', '', '92', '120', '73', '']
Column5

--
48
30
78
36
99

74
35
37
37
36

42
44
46
43
35

51
28
36
40
64

63
88
48
55
47

34
117
52
64
28

100
128
91

--
--
40
54
50
52

101
60
40
30
35

42
39
56
32
36

67
17
40
41
34

93
93
45
56
49

32
116
47
74
18

108
128
81


['', '--', '48', '30', '78', '36', '99', '', '74', '35', '37', '37', '36', '', '42', '44', '46', '43', '35', '', '51', '28', '36', '40', '64', '', '63', '88', '48', '55', '47', '', '34', '117', '52', '64', '28', '', '100', '128', '91', '', '--', '--', '40', '54', '50', '52', '', '101', '60', '40', '30', '35', '', '42', '39', '56', '32', '36', '', '67', '17', '40', '41', '34', '', '93', '93', '45', '56', '49', '', '32', '116', '47', '74', '18', '', '108', '128', '81', '']

In [490]:
# append to data to show current business cycle as this is not included in the data
listone.append('June 2009')
listtwo.append('September 2010')
listthree.append('15')
listfour.append('108+')

In [333]:
#Create a DataFrame from the data and visualize into pandas table
BC = {'Business Cycle Dates (Peak)': listone,'Business Cycle Dates (Trough)' : listtwo,'Contraction (months)' : listthree, 'Expansion (months)' : listfour}
df = pd.DataFrame(data = BC)
df

,Business Cycle Dates (Peak),Business Cycle Dates (Trough),Contraction (months),Expansion (months)
0,,,,
1,,December 1854 (IV),--,--
2,June 1857(II),December 1858 (IV),18,30
3,October 1860(III),June 1861 (III),8,22
4,April 1865(I),December 1867 (I),32,46
5,June 1869(II),December 1870 (IV),18,18
6,October 1873(III),March 1879 (I),65,34
7,,,,
8,March 1882(I),May 1885 (II),38,36
9,March 1887(II),April 1888 (I),13,22
10,July 1890(III),May 1891 (II),10,27
11,January 1893(I),June 1894 (II),17,20
12,December 1895(IV),June 1897 (II),18,18
13,,,,
14,June 1899(III),December 1900 (IV),18,24
15,September 1902(IV),August 1904 (III),23,21
16,May 1907(II),June 1908 (II),13,33
17,January 1910(I),January 1912 (IV),24,19
18,January 1913(I),December 1914 (IV),23,12
19,,,,
20,August 1918(III),March 1919 (I),7,44
21,January 1920(I),July 1921 (III),18,10
22,May 1923(II),July 1924 (III),14,22
23,October 1926(III),November 1927 (IV),13,27
24,August 1929(III),March 1933 (I),43,21
25,,,,
26,May 1937(II),June 1938 (II),13,50
27,February 1945(I),October 1945 (IV),8,80
28,November 1948(IV),October 1949 (IV),11,37
29,July 1953(II),May 1954 (II),10,45
30,August 1957(III),April 1958 (II),8,39
31,,,,
32,April 1960(II),February 1961 (I),10,24
33,December 1969(IV),November 1970 (IV),11,106
34,November 1973(IV),March 1975 (I),16,36
35,January 1980(I),July 1980 (III),6,58
36,July 1981(III),November 1982 (IV),16,12
37,,March 1991(I),,
38,July 1990(III),,8,92
39,March 2001(I),November 2001 (IV),8,120
40,December 2007 (IV),June 2009 (II),18,73
41,,,,
42,June 2009,September 2010,15,108+

In [523]:
#drop empty rows
listint = [0,7,13,19,25,31,41]
df.drop(df.index[listint])

,Business Cycle Dates (Peak),Business Cycle Dates (Trough),Contraction (months),Expansion (months)
1,,December 1854 (IV),--,--
2,June 1857(II),December 1858 (IV),18,30
3,October 1860(III),June 1861 (III),8,22
4,April 1865(I),December 1867 (I),32,46
5,June 1869(II),December 1870 (IV),18,18
6,October 1873(III),March 1879 (I),65,34
8,March 1882(I),May 1885 (II),38,36
9,March 1887(II),April 1888 (I),13,22
10,July 1890(III),May 1891 (II),10,27
11,January 1893(I),June 1894 (II),17,20
12,December 1895(IV),June 1897 (II),18,18
14,June 1899(III),December 1900 (IV),18,24
15,September 1902(IV),August 1904 (III),23,21
16,May 1907(II),June 1908 (II),13,33
17,January 1910(I),January 1912 (IV),24,19
18,January 1913(I),December 1914 (IV),23,12
20,August 1918(III),March 1919 (I),7,44
21,January 1920(I),July 1921 (III),18,10
22,May 1923(II),July 1924 (III),14,22
23,October 1926(III),November 1927 (IV),13,27
24,August 1929(III),March 1933 (I),43,21
26,May 1937(II),June 1938 (II),13,50
27,February 1945(I),October 1945 (IV),8,80
28,November 1948(IV),October 1949 (IV),11,37
29,July 1953(II),May 1954 (II),10,45
30,August 1957(III),April 1958 (II),8,39
32,April 1960(II),February 1961 (I),10,24
33,December 1969(IV),November 1970 (IV),11,106
34,November 1973(IV),March 1975 (I),16,36
35,January 1980(I),July 1980 (III),6,58
36,July 1981(III),November 1982 (IV),16,12
37,,March 1991(I),,
38,July 1990(III),,8,92
39,March 2001(I),November 2001 (IV),8,120
40,December 2007 (IV),June 2009 (II),18,73
42,June 2009,September 2010,15,108+

Looking at the table above we can see that the economy continually goes through contractions and expansions. A contraction starts at the peak of a business cycle and ends at the trough. The last contraction, or recession, occured in December of 2007 till September 20th, 2010, in what is known as 'The Great Recession'. Since then, the US economy has been in an expansion phase. At over 108+ a month, this expansion could be the longest in US history. While this is generally a good sign, it also means that we can expect a slow down soon enough. How soon? Well, no one knows. Thus we are on the upside of economic business cycle, and this can be explained further by looking at more specific economic indicators, that show the US is currently in a good economic condition and is expected to continue.

---------------------------------------------------------------------------------------------------------------------

# Section #2

To gain a more in depth understanding of where we are it is important to look at lagging indicators. Acccording to Investopedia, a lagging indicator is 'a measurable economic factor that changes only after the economy has begun to follow a particular pattern or trend'. That means that lagging indicators only change after the fact. For example, unemployment numbers only change after the economy has been on the rise. It does not anticpate economic changes, but rather the unemployment rate goes up or down depending on the economy. So let us look at the unemployment rate to help paint the picture of the economy.

In [391]:
#assign variable for unemplyoment data
Unemployment_Data = 'Unemployment Rate.csv'
Unemployment = pd.read_csv(Unemployment_Data)

In [392]:
print(Unemployment)

   LOCATION INDICATOR SUBJECT MEASURE FREQUENCY  TIME     Value  Flag Codes
0       USA     UNEMP     TOT   PC_LF         A  1955  4.383333         NaN
1       USA     UNEMP     TOT   PC_LF         A  1956  4.141667         NaN
2       USA     UNEMP     TOT   PC_LF         A  1957  4.258333         NaN
3       USA     UNEMP     TOT   PC_LF         A  1958  6.800000         NaN
4       USA     UNEMP     TOT   PC_LF         A  1959  5.475000         NaN
5       USA     UNEMP     TOT   PC_LF         A  1960  5.508333         NaN
6       USA     UNEMP     TOT   PC_LF         A  1961  6.683333         NaN
7       USA     UNEMP     TOT   PC_LF         A  1962  5.541667         NaN
8       USA     UNEMP     TOT   PC_LF         A  1963  5.666667         NaN
9       USA     UNEMP     TOT   PC_LF         A  1964  5.191667         NaN
10      USA     UNEMP     TOT   PC_LF         A  1965  4.525000         NaN
11      USA     UNEMP     TOT   PC_LF         A  1966  3.783333         NaN
12      USA     UNEMP     TOT   PC_LF         A  1967  3.841667         NaN
13      USA     UNEMP     TOT   PC_LF         A  1968  3.583333         NaN
14      USA     UNEMP     TOT   PC_LF         A  1969  3.508333         NaN
15      USA     UNEMP     TOT   PC_LF         A  1970  4.933333         NaN
16      USA     UNEMP     TOT   PC_LF         A  1971  5.958333         NaN
17      USA     UNEMP     TOT   PC_LF         A  1972  5.616667         NaN
18      USA     UNEMP     TOT   PC_LF         A  1973  4.891667         NaN
19      USA     UNEMP     TOT   PC_LF         A  1974  5.591667         NaN
20      USA     UNEMP     TOT   PC_LF         A  1975  8.466666         NaN
21      USA     UNEMP     TOT   PC_LF         A  1976  7.716667         NaN
22      USA     UNEMP     TOT   PC_LF         A  1977  7.066667         NaN
23      USA     UNEMP     TOT   PC_LF         A  1978  6.066667         NaN
24      USA     UNEMP     TOT   PC_LF         A  1979  5.833333         NaN
25      USA     UNEMP     TOT   PC_LF         A  1980  7.141667         NaN
26      USA     UNEMP     TOT   PC_LF         A  1981  7.600000         NaN
27      USA     UNEMP     TOT   PC_LF         A  1982  9.708333         NaN
28      USA     UNEMP     TOT   PC_LF         A  1983  9.616667         NaN
29      USA     UNEMP     TOT   PC_LF         A  1984  7.525000         NaN
..      ...       ...     ...     ...       ...   ...       ...         ...
33      USA     UNEMP     TOT   PC_LF         A  1988  5.491667         NaN
34      USA     UNEMP     TOT   PC_LF         A  1989  5.266667         NaN
35      USA     UNEMP     TOT   PC_LF         A  1990  5.616667         NaN
36      USA     UNEMP     TOT   PC_LF         A  1991  6.816667         NaN
37      USA     UNEMP     TOT   PC_LF         A  1992  7.508333         NaN
38      USA     UNEMP     TOT   PC_LF         A  1993  6.900000         NaN
39      USA     UNEMP     TOT   PC_LF         A  1994  6.083333         NaN
40      USA     UNEMP     TOT   PC_LF         A  1995  5.608333         NaN
41      USA     UNEMP     TOT   PC_LF         A  1996  5.416667         NaN
42      USA     UNEMP     TOT   PC_LF         A  1997  4.950000         NaN
43      USA     UNEMP     TOT   PC_LF         A  1998  4.508333         NaN
44      USA     UNEMP     TOT   PC_LF         A  1999  4.216667         NaN
45      USA     UNEMP     TOT   PC_LF         A  2000  3.991667         NaN
46      USA     UNEMP     TOT   PC_LF         A  2001  4.733333         NaN
47      USA     UNEMP     TOT   PC_LF         A  2002  5.775000         NaN
48      USA     UNEMP     TOT   PC_LF         A  2003  5.991667         NaN
49      USA     UNEMP     TOT   PC_LF         A  2004  5.533333         NaN
50      USA     UNEMP     TOT   PC_LF         A  2005  5.066667         NaN
51      USA     UNEMP     TOT   PC_LF         A  2006  4.616667         NaN
52      USA     UNEMP     TOT   PC_LF         A  2007  4.616667         NaN
53      USA     UNEMP     TOT   PC_LF         A  2008  5.775000         NaN
54      USA     UNEMP     TOT   PC_LF         A  2009  9.266666         NaN
55      USA     UNEMP     TOT   PC_LF         A  2010  9.616667         NaN
56      USA     UNEMP     TOT   PC_LF         A  2011  8.950000         NaN
57      USA     UNEMP     TOT   PC_LF         A  2012  8.066667         NaN
58      USA     UNEMP     TOT   PC_LF         A  2013  7.375000         NaN
59      USA     UNEMP     TOT   PC_LF         A  2014  6.166667         NaN
60      USA     UNEMP     TOT   PC_LF         A  2015  5.291667         NaN
61      USA     UNEMP     TOT   PC_LF         A  2016  4.866667         NaN
62      USA     UNEMP     TOT   PC_LF         A  2017  4.350000         NaN

[63 rows x 8 columns]

In [501]:
Unemployment_Data = 'Unemployment Rate.csv'
Unemployment = pd.read_csv(Unemployment_Data)

#visualize unemployment using line graph

x4 = Unemployment['TIME']
y4 = Unemployment['Value']

trace = go.Scatter(
    x = x4,
    y = y4
)

data = [trace]

layout = dict(title = 'Unemployment Rate',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'Unemployment %'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig)

Looking at the line graph above, we can see that the US is in a really good spot in terms of unemployment. The current rate is circling around 4%, the best unemployment rate since the early 2000's. However, while this is indicative of a strong economy, it is also important to look at structural unemployment, or those unemployed for 6 months or longer.

In [535]:
#bring in data for manipulation
LT_Unemployment_data = 'Long Term Unemployment Global.csv'
LT_Unemployment = pd.read_csv(LT_Unemployment_data)
print(LT_Unemployment)

   LOCATION INDICATOR SUBJECT   MEASURE FREQUENCY  TIME      Value  Flag Codes
0       AUS   LTUNEMP     TOT  PC_UNEMP         A  2017  23.456448         NaN
1       AUT   LTUNEMP     TOT  PC_UNEMP         A  2017  33.425434         NaN
2       BEL   LTUNEMP     TOT  PC_UNEMP         A  2017  50.012467         NaN
3       CAN   LTUNEMP     TOT  PC_UNEMP         A  2017  12.096099         NaN
4       CZE   LTUNEMP     TOT  PC_UNEMP         A  2017  35.983304         NaN
5       DNK   LTUNEMP     TOT  PC_UNEMP         A  2017  22.867049         NaN
6       FIN   LTUNEMP     TOT  PC_UNEMP         A  2017  24.862881         NaN
7       FRA   LTUNEMP     TOT  PC_UNEMP         A  2017  44.031566         NaN
8       DEU   LTUNEMP     TOT  PC_UNEMP         A  2017  41.910771         NaN
9       GRC   LTUNEMP     TOT  PC_UNEMP         A  2017  72.826038         NaN
10      HUN   LTUNEMP     TOT  PC_UNEMP         A  2017  41.323172         NaN
11      ISL   LTUNEMP     TOT  PC_UNEMP         A  2017   9.235151         NaN
12      IRL   LTUNEMP     TOT  PC_UNEMP         A  2017  47.045152         NaN
13      ITA   LTUNEMP     TOT  PC_UNEMP         A  2017  58.794592         NaN
14      JPN   LTUNEMP     TOT  PC_UNEMP         A  2017  36.723164         NaN
15      KOR   LTUNEMP     TOT  PC_UNEMP         A  2017   1.309233         NaN
16      LUX   LTUNEMP     TOT  PC_UNEMP         A  2017  42.580315         NaN
17      MEX   LTUNEMP     TOT  PC_UNEMP         A  2017   1.955706         NaN
18      NLD   LTUNEMP     TOT  PC_UNEMP         A  2017  40.677757         NaN
19      NZL   LTUNEMP     TOT  PC_UNEMP         A  2017  15.643398         NaN
20      NOR   LTUNEMP     TOT  PC_UNEMP         A  2017  15.629349         NaN
21      POL   LTUNEMP     TOT  PC_UNEMP         A  2017  31.026159         NaN
22      PRT   LTUNEMP     TOT  PC_UNEMP         A  2017  49.953285         NaN
23      SVK   LTUNEMP     TOT  PC_UNEMP         A  2017  58.795244         NaN
24      ESP   LTUNEMP     TOT  PC_UNEMP         A  2017  44.480285         NaN
25      SWE   LTUNEMP     TOT  PC_UNEMP         A  2017  16.815834         NaN
26      CHE   LTUNEMP     TOT  PC_UNEMP         A  2017  37.867351         NaN
27      TUR   LTUNEMP     TOT  PC_UNEMP         A  2017  21.865045         NaN
28      GBR   LTUNEMP     TOT  PC_UNEMP         A  2017  26.022451         NaN
29      USA   LTUNEMP     TOT  PC_UNEMP         A  2017  15.105956         NaN
30      G7M   LTUNEMP     TOT  PC_UNEMP         A  2017  31.025733         NaN
31      BGR   LTUNEMP     TOT  PC_UNEMP         A  2017  55.656037         NaN
32      HRV   LTUNEMP     TOT  PC_UNEMP         A  2017  42.457155         NaN
33      CYP   LTUNEMP     TOT  PC_UNEMP         A  2017  41.369879         NaN
34      EST   LTUNEMP     TOT  PC_UNEMP         A  2017  33.483207         NaN
35      ISR   LTUNEMP     TOT  PC_UNEMP         A  2017  11.587822         NaN
36      LVA   LTUNEMP     TOT  PC_UNEMP         A  2017  38.480270         NaN
37      LTU   LTUNEMP     TOT  PC_UNEMP         A  2017  38.061044         NaN
38      MKD   LTUNEMP     TOT  PC_UNEMP         A  2017  78.404614         NaN
39      MLT   LTUNEMP     TOT  PC_UNEMP         A  2017  46.719142         NaN
40      RUS   LTUNEMP     TOT  PC_UNEMP         A  2017  30.428426         NaN
41      SVN   LTUNEMP     TOT  PC_UNEMP         A  2017  48.360608         NaN
42      ZAF   LTUNEMP     TOT  PC_UNEMP         A  2017  60.440989         NaN
43     OECD   LTUNEMP     TOT  PC_UNEMP         A  2017  30.982175         NaN
44      ROU   LTUNEMP     TOT  PC_UNEMP         A  2017  41.606616         NaN
45     EU28   LTUNEMP     TOT  PC_UNEMP         A  2017  45.070329         NaN
46      COL   LTUNEMP     TOT  PC_UNEMP         A  2017   8.410032         NaN
47      CRI   LTUNEMP     TOT  PC_UNEMP         A  2017  14.709562         NaN
48      NAM   LTUNEMP     TOT  PC_UNEMP         A  2017  12.412661         NaN

In [531]:
#create bar graph for structurally unemployed

x4 = LT_Unemployment['LOCATION'] 
y4 = LT_Unemployment['Value']

data  = go.Data([
            go.Bar(
              x = x4,
              y = y4,
              
        )])
layout = go.Layout(
        title = "Structural Unemployment"
)
fig  = go.Figure(data=data, layout=layout)
py.iplot(fig)

/anaconda3/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.

As seen above, the USA has a rate of 15.1% structural unemployment. So out of the 4% that are unemployed, about 15% have been unemployed for 6+ months. While this isn't too bad in comparison to the rest of the world, it is still slightly worrysome. Structural Unemployment is a mismatch between the jobs available and the skill levels of the unemployed. If this is increasing, it means people are not learning the necessary skills required to work in today's day and age and are left behind.

------------------------------------------------------------------------------------------------------------------

# Section 3

Now we will talk about leading indicators, and more specifically the yield curve. According to Investopedia, 'A leading indicator is any economic factor that changes before the rest of the economy begins to go in a particular direction. Leading indicators help market observers and policymakers predict significant changes in the economy'. However, leading indicators are not always accurate in predicting the state of the economy. The Yield Curve is a line that plots the interest rates, at a set point in time, of bonds having equal credit quality but differing maturity dates. When talking about the yield curve, it is usually in reference to the treasury yield curve, which plots US treasuries yield against their maturity. The graph below will be a visualization of the treasury yield curve.

In [459]:
#bring in treasury for manipulation
Treasury_Yield_data = 'Treasury Yields.xlsx'
Treasury_Yield = pd.read_excel(Treasury_Yield_data)
print(Treasury_Yield)

         Year  30 Year Treasury Rate  10 Year Treasury Rate  90 Day Treasury
0  1997-01-01               6.606760               6.352500          5.060833
1  1998-01-01               5.576800               5.264167          4.776667
2  1999-01-01               5.872231               5.636667          4.638333
3  2000-01-01               5.940637               6.029167          5.816667
4  2001-01-01               5.494839               5.017500          3.388333
5  2002-01-01               5.433848               4.610833          1.602500
6  2003-01-01               5.323486               4.015000          1.010833
7  2004-01-01               5.267403               4.274167          1.371667
8  2005-01-01               5.128374               4.290000          3.146667
9  2006-01-01               4.913036               4.791667          4.726667
10 2007-01-01               4.838287               4.629167          4.353333
11 2008-01-01               4.277530               3.666667          1.365000
12 2009-01-01               4.076640               3.256667          0.150000
13 2010-01-01               4.251076               3.214167          0.136667
14 2011-01-01               3.910800               2.785833          0.052500
15 2012-01-01               2.921680               1.802500          0.085833
16 2013-01-01               3.446160               2.350833          0.058333
17 2014-01-01               3.338160               2.540833          0.032500
18 2015-01-01               2.840996               2.135833          0.052500
19 2016-01-01               2.594400               1.841667          0.317500
20 2017-01-01               2.894040               2.330000          0.930833

In [502]:
#plot 30 year, 10 year, and 3 month yield curve on same graph, using three different traces

x5 = Treasury_Yield['Year']
y5 = Treasury_Yield['30 Year Treasury Rate']
y6 = Treasury_Yield['10 Year Treasury Rate']
y7 = Treasury_Yield['90 Day Treasury ']

trace = go.Scatter(
    x = x5,
    y = y5,
    name = '30 Year'
)

trace1 = go.Scatter(
    x = x5,
    y = y6,
    name = '10 Year'
)

trace2 = go.Scatter(
    x = x5,
    y = y7,
    name = '3 Month'
)

data = [trace, trace1, trace2]

layout = dict(title = '90-Day, 10-Year, & 30-Year Treasury Rate (Annual)',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'Yield'),
              )

fig = dict(data=data, layout=layout)
py.iplot(fig)

What we are looking for in this graph is an 'Inverted yield curve'. This is where the yield for a shorter maturity bond, for example the 3-month treasury, has a higher yield than a longer maturity bond, like the 10-year. This is generally a bad sign for the economy as investors are not willing to put their money in long term treasuries backed by the US government, but rather are shifting their investments towards shorter term maturities, indicating a lack of trust in the longer term. In the 21st century, this only happened once, a year before a start of the great recession. The following article says https://money.cnn.com/2005/12/27/news/economy/inverted_yield_curve/index.htm that the inverted yeild curve we can see in 2006 was "An exception to the rule". Obviously that did not turn out to be the case. Recently there have been worries amongst investors of another inverted yield curve, as the 30-year has been decreasing recently while the 10-year and 90-day have been increasing. Whether or not a recession is coming is up for each individual to decide themselves. And finally, it is important to look at the levels of US federal debt over the years.

------------------------------------------------------------------------------------------------------------------

Federal Debt, which is described as the US's achilles Heel has been rapidly expanding since the 20th century. To get a further understanding lets take a look at what has been happening.

In [461]:
Federal_Debt_data = 'Federal Debt.xls'
Federal_Debt = pd.read_excel(Federal_Debt_data)
print(Federal_Debt)

         Year  Federal Debt as a % of GDP  Federal Debt
0  1972-01-01                   33.943025     434049.50
1  1973-01-01                   32.383967     461402.50
2  1974-01-01                   31.104870     480510.00
3  1975-01-01                   32.231185     543285.75
4  1976-01-01                   33.477657     627291.50
5  1977-01-01                   33.165555     690353.75
6  1978-01-01                   32.425443     761931.50
7  1979-01-01                   31.152237     818335.00
8  1980-01-01                   31.314180     894744.00
9  1981-01-01                   30.885198     990572.25
10 1982-01-01                   33.480492    1120009.50
11 1983-01-01                   36.801853    1337996.75
12 1984-01-01                   38.440668    1552917.75
13 1985-01-01                   41.776820    1813604.00
14 1986-01-01                   45.764798    2096576.00
15 1987-01-01                   48.075047    2334503.00
16 1988-01-01                   49.272937    2580445.50
17 1989-01-01                   50.293160    2837811.50
18 1990-01-01                   53.626280    3198461.25
19 1991-01-01                   58.727312    3617544.50
20 1992-01-01                   61.749187    4026893.50
21 1993-01-01                   63.887838    4382426.50
22 1994-01-01                   64.202962    4678642.75
23 1995-01-01                   64.724383    4944534.00
24 1996-01-01                   64.498267    5206711.25
25 1997-01-01                   63.177690    5418143.75
26 1998-01-01                   61.338932    5557692.75
27 1999-01-01                   58.996943    5680689.25
28 2000-01-01                   55.606675    5698931.25
29 2001-01-01                   54.931917    5812864.50
30 2002-01-01                   56.607157    6191611.00
31 2003-01-01                   58.708173    6728045.25
32 2004-01-01                   60.133432    7345149.75
33 2005-01-01                   60.820637    7929139.50
34 2006-01-01                   61.488585    8494599.00
35 2007-01-01                   62.193835    8988541.75
36 2008-01-01                   67.397672    9913532.50
37 2009-01-01                   81.123005   11723348.25
38 2010-01-01                   89.292312   13390438.00
39 2011-01-01                   94.285682   14656620.25
40 2012-01-01                   98.714388   15990131.25
41 2013-01-01                  100.398053   16851000.00
42 2014-01-01                  101.596812   17799837.00
43 2015-01-01                  100.684865   18344212.75
44 2016-01-01                  104.498857   19549200.50
45 2017-01-01                  103.190523   20107155.25

In [503]:
#graph federal debt on bar graph while fed debt as % of gdp in a line

x6 = Federal_Debt['Year']
y8 = Federal_Debt['Federal Debt as a % of GDP']
y9 = Federal_Debt['Federal Debt']

trace3 = go.Scatter(
    x= x6,
    y= y8,
    mode = 'lines+markers',
    name = '% of GDP'   
)

trace4 = go.Bar(
    x= x6,
    y= y9,
    name = 'Federal Debt'
)

layout = dict(title = 'Rapid Expansion of U.S. Federal Debt',
              xaxis = dict(title = 'Year'),
              yaxis = dict(title = 'Federal Government public debt'),
              )

data = [trace3, trace4]
fig = dict(data=data, layout=layout)
py.iplot(fig, filename='bar-line')

As we can see above, Federal Debt expanding at an extraordinary level throughout the 1990's and 2000's, eventually reaching over a 100% of GDP. This is worrysome in the long term, especially for the younger generation as the numbers continue to climb. The government will eventually have to take care of this issue as it is a ticking time bomb.

# Conclusion

Overall, the US economy is in a good spot, especially in the short term. Looking solely at the indicators brought forth in this notebook, they all signal a robust economy. However, in the long term it is important to remember things such as structural unemployment and the growing federal debt. Moreover, as with every cycle, things eventually take a downturn.